name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Package
      run: |
        mkdir -p packages
        tar -czvf packages/alc-linux.tar.gz linux
        zip -r packages/alc-win32.zip win32
        tar -czvf packages/alc-darwin.tar.gz darwin

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          packages/alc-linux.tar.gz
          packages/alc-win32.zip
          packages/alc-darwin.tar.gz