name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Package
      run: |
        mkdir -p packages
        tar -czvf packages/alc-linux.tar.gz linux
        zip -r packages/alc-win32.zip win32
        tar -czvf packages/alc-darwin.tar.gz darwin

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: packages/alc-linux.tar.gz
        asset_name: alc-linux.tar.gz
        asset_content_type: application/gzip

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: packages/alc-win32.zip
        asset_name: alc-win32.zip
        asset_content_type: application/zip

    - name: Upload Darwin Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: packages/alc-darwin.tar.gz
        asset_name: alc-darwin.tar.gz
        asset_content_type: application/gzip
